### ISSUE TITLE
Unable to figure out configuration when "in-source" is false

### ISSUE THREAD

**Issue by claudebarde** [bloodyowl/rescript-test#8]
Hi!
I use `in-source:false` in my BS configuration to compile the JavaScript files in a different folder outside of my ReScript project. I tried different solutions to get the test file to be compiled outside of the main directory but I couldn't make it work. The error message I get may suggest that there is no `bin` folder because my JS files get compiled in a `lib` folder.
Here is the repo for the project I am trying to add tests to: https://github.com/claudebarde/rescript-michelson
Thank you for your help!

**Comment by bloodyowl** [comment]
Your test files output are located in `lib/es6/tests`, so your `test` command should be `retest lib/es6/tests/*.mjs`. That should make it work 😊

**Comment by claudebarde** [comment]
It wasn't working at first but it started working after running `rescript clean -with-deps` for some reason. Thank you!
